### ISSUE TITLE
Experimental Chrome implementation not working when rendered from React

### ISSUE THREAD

**Issue by steobrien** [mfreed7/declarative-shadow-dom#7]
On Chrome Canary, I see declarative shadow dom working in [your example](https://output.jsbin.com/huquloz) 🎉 
![image](https://user-images.githubusercontent.com/1694410/80295557-af2ff080-8741-11ea-9cbd-0c53569ca91b.png)

However, when I [embed identical markup in a shell React app](https://fsrn3.csb.app/),  only the slotted content appears:
![image](https://user-images.githubusercontent.com/1694410/80295580-e1d9e900-8741-11ea-9109-3071dcf2d689.png)

The inspector shows that the `<template shadowroot="open">` element has not been transformed in this case:
![image](https://user-images.githubusercontent.com/1694410/80295601-07ff8900-8742-11ea-990e-5277782616cb.png)

Any clues on why it didn't get transformed?

Thank you for your diligent work in pushing this forward.

**Comment by mfreed7** [comment]
Thanks for the issue and the example! It would seem that the reason for this issue is that React/Babel transforms `<template shadowroot="open">` into this:

```javascript
}, _react.default.createElement("template", {
    shadowroot: "open",
    __source: {
      fileName: _jsxFileName,
      lineNumber: 22
    }
```

And React's createElement will first create a `<template>` element, and then add a "shadowroot" attribute. And as-[proposed](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md#other-details--questions), that just results in a "normal" template with a "shadowroot" attribute.

I think to support this use case, React will have to be made "declarative Shadow DOM aware" by parsing this more directly into native HTML as `<template shadowroot="open">`, or more likely by converting it to a call to `attachShadow()`.

**Comment by steobrien** [comment]
Got it. Thanks for explaining. I’ll look into this a little more.

**Comment by steobrien** [comment]
Closing: this is as per the proposed spec. The part I missed:
>  The entire [motivation](#motivation) for this feature is no-JS environments; therefore, to simplify the implementation, only **parser-generated** templates will create shadow roots, and adding the shadowroot attribute to a `<template>` after the fact will have no effect. To create a shadowroot using JS, the existing `element.attachShadow()` API should be used.

For posterity, I note that direct addition of HTML through JavaScript works (in the current implementation):
```js
document.body.innerHTML = "<div><template shadowroot=open>displayed in shadow dom</template></div>"
```
